<?php

namespace app\models;

use Illuminate\Database\Eloquent\Model;


class M_Users extends Model
{

    protected $table = 'm_users';

    public function hasManyRelationMenus()
    {
        return parent::hasMany('app\models\M_RelationMenus', 'user_id', 'id'); // TODO: Change the autogenerated stub
    }


}